### ISSUE TITLE
For the pre-trained weights

### ISSUE THREAD

**Issue by stonewalking** [YUCHEN005/GILA#3]
Hello author, 

I am quite interest in your work and code here,

Would you please provide the backbone weights, as the dataset is hard to require.

**Comment by YUCHEN005** [comment]
Hi, we may not release pretrained model due to proj copyright at this time, maybe later this year, sorry for inconvenience

you can find datasets at: https://mmai.io/datasets/lip_reading/ (LRS3) and https://www.robots.ox.ac.uk/~vgg/data/lip_reading/lrs2.html (LRS2)

We also apply for the data from authors, which seems not hard..
